# Neural Networkds

Neural networks, also known as artificial neural networks, are a type of machine learning algorithm that is inspired by the structure and function of the human brain. They are composed of multiple interconnected nodes or neurons, organized into layers that perform complex computations on input data.

The basic idea behind neural networks is to learn from data by adjusting the weights and biases of the neurons through a process called backpropagation. This process involves iteratively comparing the output of the network to the desired output, and then updating the weights and biases to minimize the error.

Neural networks can be used for a variety of tasks, such as classification, regression, and clustering, and they have been successfully applied to a wide range of domains, including image and speech recognition, natural language processing, and game playing.

While neural networks have shown impressive performance in many applications, they can also be difficult to train and may suffer from overfitting, where the network performs well on the training data but fails to generalize to new data. As a result, a lot of research is still being done to improve the performance and usability of neural networks.

Here we will try to make our own neural networks from scratch

* This notebook is highly inspired from the book [nnfs](https://nnfs.io/), consider checking out the book :)

Some points to rememeber
* Formula for the output of a neural network $$output = weight * input + bias$$
```
output = (weight * input) + bias
```
You can think that 
* * len of `bias` shows the number of output neurons
* * len of `input` shows the number of input neurons
* * len of `weight` shows the relationship between these two  

Lets say we have a two neurons, one gives the input, and one gives the output, there will be one weight, one input and one bias related, lets try to find out the output of that one neuron, like this

<img src = "https://i0.wp.com/thedeconvertedman.com/wp-content/uploads/2020/11/Connecting-the-Dots-Image-3.png?fit=300%2C300&ssl=1">



Lets say we have a prededifined weight, input and bias

In [91]:
input = 1
weight = 0.2
bias = 2

Applying the fromula we get 

In [92]:
(input * weight) + bias

2.2

So now we have created our first pair of neurons, now we will try to make it complicated. What if we are total of $4$ neurons , where $1$ neuron is taking input from $3$ neurons. So there will be $3$ inputs, $3$ wieghts and one bais. Lets try to find the output of that one neuron, like this 

<img src = "https://osghaffar.github.io/images/basicNN.png" height = 400px>

In [94]:
inputs = [1 , 2 , 3]
weights = [0.2 , 0.8 , -0.5]
bais = 2

In [95]:
(inputs[0] * weights[0]) + (inputs[1] * weights[1]) + (inputs[2] * weights[2]) + bias

2.3

Lets try for 4, like this 

<img src = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqIcBfxcoo377sDczVbTHLTW7F7ZURld8CLA&usqp=CAU" height = 400px >

In [97]:
inputs = [1 , 2 , 3 , 2.5]
weights = [0.2 , 0.8 , -0.5 , 1]
bais = 2

In [98]:
(inputs[0] * weights[0]) + (inputs[1] * weights[1]) + (inputs[2] * weights[2]) + (inputs[3] * weights[3]) + bias

4.8

Lets try with a list of bias and a list of weights 

In [99]:
inputs = [1 , 2 , 3 , 2.5]
weights_1 = [0.2 , 0.8 , -0.5 , 1]
weights_2 = [0.5 , -0.91 , 0.26 , -0.5]
weights_3 = [-0.26 , -0.27 , 0.17 , 0.87]
bias_1 = 2
bias_2 = 3
bias_3 = 0.5

In [100]:
output = [inputs[0] * weights_1[0] + inputs[1] * weights_1[1] + inputs[2] * weights_1[2] + inputs[3] * weights_1[3] + bias_1 , 
          inputs[0] * weights_2[0] + inputs[1] * weights_2[1] + inputs[2] * weights_2[2] + inputs[3] * weights_2[3] + bias_2 , 
          inputs[0] * weights_3[0] + inputs[1] * weights_3[1] + inputs[2] * weights_3[2] + inputs[3] * weights_3[3] + bias_3]

In [101]:
output

[4.8, 1.21, 2.385]

Instead of writing this much of hard coding, we can just iterate loops like this 

In [102]:
inputs = [1 , 2 , 3 , 2.5]
weights = [[0.2 , 0.8 , -0.5 , 1] , 
             [0.5 , -0.91 , 0.26 , -0.5] , 
             [-0.26 , -0.27 , 0.17 , 0.87]]
baises  = [2 , 3 , 0.5]

In [103]:
output = []

for weight , bais in zip(weights , baises):

    neuron_out = 0

    for input , weigh in zip(inputs , weight):

        neuron_out += input*weigh

    neuron_out += bais
    output.append(neuron_out)

In [104]:
output

[4.8, 1.21, 2.385]

Notice we got the same answer

Instead of iterating over the loop, we can just use the dot product of the two and add the bias then
We will first try this on 1 neuron with 3 inputs

In [105]:
inputs = np.array([1 , 2 , 3 , 2.5])
weights = np.array([0.2 , 0.8 , -0.5 , 1])
bais = 2

In [106]:
import numpy as np

In [107]:
output = np.dot(inputs , weights) + bais

In [108]:
output

4.799999952316284

The output is different because of differnet data types used in core python and numpy

Lets try the same with a bunch of neurons

In [110]:
inputs = np.array([1 , 2 , 3 , 2.5])

weights = np.array([[0.2 , 0.8 , -0.5 , 1] , 
             [0.5 , -0.91 , 0.26 , -0.5] , 
             [-0.26 , -0.27 , 0.17 , 0.87]])

baises  = np.array([2 , 3 , 0.5])


In [111]:
output = np.dot(inputs , weights) + baises

ValueError: ignored

We got a shape error, thats becayse we are trying to make a dot product of two matrix which are inconsistent , for this, we just need to transpose one of them



In [113]:
output = np.dot(inputs , weights.T) + baises

In [114]:
output

array([4.79999995, 1.21000004, 2.38499999])

And we got almost the same answers

Now lets try doing the same with a bunch of neurons

In [115]:
inputs = np.array([[1 , 2 , 3 , 2.5] , 
                   [2 , 5 , -1 , 2] , 
                   [-1.5 , 2.7 , 3.3 , -0.8]])

weights = np.array([[0.2 , 0.8 , -0.5 , 1] , 
             [0.5 , -0.91 , 0.26 , -0.5] , 
             [-0.26 , -0.27 , 0.17 , 0.87]])

baises  = np.array([2 , 3 , 0.5])

In [116]:
output = np.dot(inputs , weights.T) + baises

In [117]:
output

array([[ 4.79999995,  1.21000004,  2.38499999],
       [ 8.9000001 , -1.80999994,  0.19999999],
       [ 1.41000003,  1.051     ,  0.02599999]])

Now lets try to add a third layer, the inputs for the third layer will be the outputs from the second layer 

In [118]:
inputs = np.array([[1 , 2 , 3 , 2.5] , 
                   [2 , 5 , -1 , 2] , 
                   [-1.5 , 2.7 , 3.3 , -0.8]])

baises_1  = np.array([2 , 3 , 0.5])

weights_1 = np.array([[0.2 , 0.8 , -0.5 , 1] , 
             [0.5 , -0.91 , 0.26 , -0.5] , 
             [-0.26 , -0.27 , 0.17 , 0.87]])

# ***************************************************************

weights_2 = np.array([[0.1 , -0.14 , 0.5] , 
                      [0.5 , 0.12 , -0.33] , 
                      [-0.44 , 0.73 , -0.13]])

baises_2 = np.array([-1 , 2 , -0.5])


In [119]:
output_1 = np.dot(inputs , weights_1.T) + baises_1

In [121]:
output_1

array([[ 4.79999995,  1.21000004,  2.38499999],
       [ 8.9000001 , -1.80999994,  0.19999999],
       [ 1.41000003,  1.051     ,  0.02599999]])

Ouput of this layer will be the inputs of the other layer 

In [120]:
output_2 = np.dot(output_1 , weights_2.T) + baises_2

In [122]:
output_2

array([[ 0.50310004,  3.75814998, -2.03874993],
       [ 0.24339998,  6.16680002, -5.76329994],
       [-0.99314   ,  2.82254004, -0.35655001]])

As we are moving futer we are increasing our scale, lets try to get help from this `nnfs` library for some simplicity in future

In [123]:
! pip install nnfs
import nnfs
nnfs.init()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Now we dont need to asign inputs everytime manually, we will just get a sample dataset from this library for inputs

In [126]:
from nnfs.datasets import spiral_data

In [128]:
x , y = spiral_data(samples = 5 , classes = 3)

In [129]:
x

array([[ 0.        ,  0.        ],
       [ 0.1068272 , -0.22602643],
       [-0.3565171 ,  0.35056463],
       [ 0.54027534, -0.52019477],
       [-0.9980913 , -0.06175594],
       [-0.        , -0.        ],
       [ 0.09934813,  0.22941218],
       [ 0.35293192, -0.35417378],
       [-0.73923534,  0.12661397],
       [ 0.97696507,  0.2133992 ],
       [ 0.        ,  0.        ],
       [-0.23611835, -0.082147  ],
       [ 0.12262503,  0.48472992],
       [ 0.49086097, -0.5670586 ],
       [-0.9298463 ,  0.36794814]], dtype=float32)

In [130]:
y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=uint8)

Lets get some random weights of a specific size

In [137]:
weights = np.random.randn(2 , 3)

In [138]:
weights

array([[-1.9807965 , -0.34791216,  0.15634897],
       [ 1.2302907 ,  1.2023798 , -0.3873268 ]], dtype=float32)

Here $2$ is the number of input and $3$ is the number of output neurons 

These values do not lie in the range of $(-1 , 1)$, so we will just divide them 

In [139]:
weights = 0.01 * np.random.randn(2 , 3)

In [140]:
weights

array([[-0.00302303, -0.01048553, -0.01420018],
       [-0.0170627 ,  0.01950775, -0.00509652]], dtype=float32)

These are much better

It is good to initialize biases as zeros as of now, so we will be using `np.zeros` function to get an array of zeros. Obviously we need $3$ baises, as we have defined that we have $3$ output neurons

In [141]:
biases = np.zeros((1 , 3))

Now we have inputs `x`, weights and baises, so lets calculate output

In [142]:
output = np.dot(x , weights) + biases

In [143]:
output

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 3.5336800e-03, -5.5294074e-03, -3.6501675e-04],
       [-4.9038185e-03,  1.0576999e-02,  3.2759465e-03],
       [ 7.2426610e-03, -1.5812904e-02, -5.0208224e-03],
       [ 4.0709805e-03,  9.2607960e-03,  1.4487815e-02],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-4.2147236e-03,  3.4335984e-03, -2.5799654e-03],
       [ 4.9762386e-03, -1.0609813e-02, -3.2066421e-03],
       [ 7.4352298e-05,  1.0221228e-02,  9.8519828e-03],
       [-6.5945592e-03, -6.0810577e-03, -1.4960673e-02],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 2.1154420e-03,  8.7332260e-04,  3.7715868e-03],
       [-8.6415010e-03,  8.1702033e-03, -4.2117340e-03],
       [ 8.1916656e-03, -1.6208977e-02, -4.0802872e-03],
       [-3.4672385e-03,  1.6927773e-02,  1.1328728e-02]], dtype=float32)

And we have the output we have desired

Now lets try to implement this in a class so that we can make diffrent layers and add neurons

In [162]:
class Dense:

    def __init__(self , inputs , neurons):
        
        self.weights = 0.01 * np.random.randn(inputs , neurons)
        self.biases = np.zeros((1 , neurons))
    
    def forward(self , inputs):
    
        self.output = np.dot(inputs , self.weights) + self.biases