# MAE 

<img src = "https://jmlb.github.io/images/20180701/img_01.png">

Mean Absolute Error (MAE) is a commonly used metric in regression analysis to evaluate the accuracy of a model's predictions. It measures the average difference between the predicted and actual values of the target variable.

The MAE is measured in the same units as the target variable, which makes it easy to interpret. A lower MAE value indicates better accuracy of the model's predictions, whereas a higher MAE value indicates poorer accuracy.

MAE has some advantages over other metrics such as mean squared error (MSE) as it is less sensitive to outliers, since it does not involve squaring the differences between actual and predicted values. However, it may not penalize larger errors as strongly as MSE.

$$MAE = \frac {1}{n}\sum\limits _{i = 1}^{n}|actual - predicted|$$


In [1]:
import numpy as np 

Lets assume we have these values

In [2]:
predicted = 12
actual = 14

The error, also can be said as the difference between these values will be

In [3]:
predicted - actual

-2

As we know this is in naegative, but we need to have a positive error, for easier computation, so we will add the mod function here 

In [4]:
abs(predicted - actual)

2

Now lets assume we have a list of values

In [5]:
actual = np.array([x for x in range(10)])
predicted = np.array([x for x in range(0 , 20 , 2)])

In [7]:
actual 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
predicted

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
abs(predicted - actual)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

If we calculate the mean of this error, it will be

In [9]:
abs(predicted - actual).mean()

4.5

This can now be said as the `mean absolute error `

Lets now put all of this into a function for better usage 

In [10]:
def MAE(predicted , actual):
    
    error = (abs(predicted - actual)).mean()

    return error